/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session Route */
        post: operations["create_session_route_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_review__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{token}/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Article Route */
        get: operations["get_review_article_route_review__token__articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{token}/articles/{article_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Route */
        post: operations["approve_route_review__token__articles__article_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{token}/articles/{article_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Changes Route */
        post: operations["request_changes_route_review__token__articles__article_id__request_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites Route */
        get: operations["list_sites_route_sites_get"];
        put?: never;
        /** Create Site Route */
        post: operations["create_site_route_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection Route */
        post: operations["test_connection_route_sites_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Site Route */
        delete: operations["delete_site_route_sites__site_id__delete"];
        options?: never;
        head?: never;
        /** Update Site Route */
        patch: operations["update_site_route_sites__site_id__patch"];
        trace?: never;
    };
    "/sites/{site_id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_sites__site_id__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/articles/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paste Article */
        post: operations["paste_article_sites__site_id__articles_paste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/articles/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Articles */
        post: operations["upload_articles_sites__site_id__articles_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_sites__site_id__articles__article_id__get"];
        put?: never;
        post?: never;
        /** Delete Article Route */
        delete: operations["delete_article_route_sites__site_id__articles__article_id__delete"];
        options?: never;
        head?: never;
        /** Update Article */
        patch: operations["update_article_sites__site_id__articles__article_id__patch"];
        trace?: never;
    };
    "/sites/{site_id}/articles/{article_id}/pull-back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pull Back Route */
        post: operations["pull_back_route_sites__site_id__articles__article_id__pull_back_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/articles/{article_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Route */
        post: operations["retry_route_sites__site_id__articles__article_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/articles/{article_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Route */
        post: operations["schedule_route_sites__site_id__articles__article_id__schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/articles/{article_id}/send-for-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send For Review Route */
        post: operations["send_for_review_route_sites__site_id__articles__article_id__send_for_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/articles/{article_id}/unschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unschedule Route */
        post: operations["unschedule_route_sites__site_id__articles__article_id__unschedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_sites__site_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/review-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Link */
        get: operations["get_review_link_sites__site_id__review_link_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/review-link/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Review Link Route */
        post: operations["reset_review_link_route_sites__site_id__review_link_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Site Connection Route
         * @description Tests the stored credentials, with any fields in the body overriding
         *     them (the edit dialog, where an empty password means the stored one).
         *     Testing exactly what is stored records the result on the site.
         */
        post: operations["test_site_connection_route_sites__site_id__test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Client Name
             * @description The client's name.
             */
            client_name: string;
            /**
             * Version
             * @description The version the client is approving.
             */
            version: number;
        };
        /** ArticleCard */
        ArticleCard: {
            /**
             * Id
             * @description Article id.
             */
            id: string;
            /**
             * Publish At Utc
             * @description Scheduled publish time, UTC.
             */
            publish_at_utc?: string | null;
            /**
             * Published Url
             * @description Live URL, once published.
             */
            published_url?: string | null;
            /**
             * Sent For Review At
             * @description When the agency last sent it for review, UTC.
             */
            sent_for_review_at?: string | null;
            /**
             * Slug
             * @description URL slug.
             */
            slug: string;
            /** @description Warning from the last WordPress status check, if any. */
            sync_warning?: components["schemas"]["SyncWarning"] | null;
            /**
             * Title
             * @description Article title.
             */
            title: string;
        };
        /** ArticleDetail */
        ArticleDetail: {
            /**
             * Approved Version
             * @description Version the client approved, if any.
             */
            approved_version?: number | null;
            /**
             * Body Html
             * @description Article body, as HTML.
             */
            body_html: string;
            /**
             * Client Comment
             * @description The client's latest change request, if any.
             */
            client_comment?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation time, UTC.
             */
            created_at: string;
            /**
             * Events
             * @description History log, oldest first.
             * @default []
             */
            events: components["schemas"]["EventOut"][];
            /**
             * Id
             * @description Article id.
             */
            id: string;
            /**
             * Last Checked At
             * @description Last WordPress status check time.
             */
            last_checked_at?: string | null;
            /**
             * Last Error
             * @description Error from the last failed WordPress call.
             */
            last_error?: string | null;
            /**
             * Publish At Utc
             * @description Scheduled publish time, UTC.
             */
            publish_at_utc?: string | null;
            /**
             * Published Url
             * @description Live URL, once published.
             */
            published_url?: string | null;
            /**
             * Slug
             * @description URL slug.
             */
            slug: string;
            /**
             * Source
             * @description How the article was imported: paste or docx.
             */
            source: string;
            /**
             * Source Filename
             * @description Original filename, if imported from a file.
             */
            source_filename?: string | null;
            /** @description Current lifecycle status. */
            status: components["schemas"]["Status"];
            /** @description Warning from the last WordPress status check, if any. */
            sync_warning?: components["schemas"]["SyncWarning"] | null;
            /**
             * Title
             * @description Article title.
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time, UTC.
             */
            updated_at: string;
            /**
             * Version
             * @description Increments on every body edit.
             */
            version: number;
            /**
             * Warnings
             * @description Warnings produced during import.
             * @default []
             */
            warnings: string[];
            /**
             * Wp Post Id
             * @description WordPress post id, once sent.
             */
            wp_post_id?: number | null;
        };
        /** ArticlePaste */
        ArticlePaste: {
            /**
             * Html
             * @description Pasted article HTML, raw body capped at 2 MB.
             */
            html: string;
        };
        /** ArticleSummary */
        ArticleSummary: {
            /**
             * Id
             * @description Article id.
             */
            id: string;
            /**
             * Last Error
             * @description Last WordPress error, for a failed article.
             */
            last_error?: string | null;
            /**
             * Publish At Utc
             * @description Scheduled publish time, UTC.
             */
            publish_at_utc?: string | null;
            /**
             * Published Url
             * @description Live URL, once published.
             */
            published_url?: string | null;
            /**
             * Slug
             * @description URL slug.
             */
            slug: string;
            /** @description Current lifecycle status. */
            status: components["schemas"]["Status"];
            /** @description Warning from the last WordPress status check, if any. */
            sync_warning?: components["schemas"]["SyncWarning"] | null;
            /**
             * Title
             * @description Article title.
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time, UTC.
             */
            updated_at: string;
        };
        /** ArticleUpdate */
        ArticleUpdate: {
            /**
             * Body Html
             * @description New body HTML, cleaned like import, capped at 2 MB.
             */
            body_html?: string | null;
            /**
             * Slug
             * @description New slug: lowercase letters, digits, hyphens.
             */
            slug?: string | null;
            /**
             * Title
             * @description New title.
             */
            title?: string | null;
        };
        /** ArticlesOut */
        ArticlesOut: {
            /**
             * Articles
             * @description All matching articles.
             */
            articles: components["schemas"]["ArticleSummary"][];
            /**
             * Wordpress Unreachable
             * @description True if the last WordPress status check failed.
             */
            wordpress_unreachable: boolean;
        };
        /** Body_upload_articles_sites__site_id__articles_upload_post */
        Body_upload_articles_sites__site_id__articles_upload_post: {
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /** ChangeRoundsEntry */
        ChangeRoundsEntry: {
            /**
             * Article Id
             * @description Article id.
             */
            article_id: string;
            /**
             * Rounds
             * @description Number of change-request rounds.
             */
            rounds: number;
            /**
             * Title
             * @description Article title.
             */
            title: string;
        };
        /** EventOut */
        EventOut: {
            /**
             * Actor
             * @description Who or what triggered the event.
             */
            actor: string;
            /**
             * At
             * Format: date-time
             * @description When the event happened, UTC.
             */
            at: string;
            /**
             * Data
             * @description The comment or error attached to this event.
             */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * @description Event id.
             */
            id: string;
            /** @description What happened. */
            type: components["schemas"]["EventType"];
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "imported" | "edited" | "sent_for_review" | "pulled_back" | "approved" | "changes_requested" | "scheduled" | "date_changed" | "published" | "failed" | "retried" | "unscheduled" | "ai_draft_created" | "ai_draft_accepted";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NeedsAttentionEntry */
        NeedsAttentionEntry: {
            /**
             * Article Id
             * @description Article id.
             */
            article_id: string;
            /**
             * Detail
             * @description Error detail, for a failed article.
             */
            detail?: string | null;
            /**
             * Reason
             * @description Why this article needs attention.
             * @enum {string}
             */
            reason: "failed" | "late" | "changed_in_wordpress" | "missing_in_wordpress";
            /**
             * Title
             * @description Article title.
             */
            title: string;
        };
        /** PublishedEntry */
        PublishedEntry: {
            /**
             * Article Id
             * @description Article id.
             */
            article_id: string;
            /**
             * Published At
             * Format: date-time
             * @description When the article went live, UTC.
             */
            published_at: string;
            /**
             * Published Url
             * @description Live URL.
             */
            published_url: string;
            /**
             * Title
             * @description Article title.
             */
            title: string;
        };
        /** ReportOut */
        ReportOut: {
            /**
             * Avg Approval Seconds
             * @description Average sent-for-review-to-approved seconds; null if none approved.
             */
            avg_approval_seconds?: number | null;
            /**
             * Avg Change Rounds
             * @description Change requests per article, over all articles; null if none.
             */
            avg_change_rounds?: number | null;
            /**
             * Change Rounds
             * @description Articles that needed changes, with rounds per article.
             */
            change_rounds: components["schemas"]["ChangeRoundsEntry"][];
            /**
             * Needs Attention
             * @description Failed articles and articles carrying a sync warning.
             */
            needs_attention: components["schemas"]["NeedsAttentionEntry"][];
            /**
             * Published
             * @description Published articles, most recent first.
             */
            published: components["schemas"]["PublishedEntry"][];
            /**
             * Published This Month
             * @description Published this calendar month, UTC.
             */
            published_this_month: number;
            /**
             * Status Counts
             * @description Article count per status.
             */
            status_counts: {
                [key: string]: number;
            };
            /**
             * Upcoming
             * @description Scheduled articles, soonest first.
             */
            upcoming: components["schemas"]["UpcomingEntry"][];
            /**
             * Wordpress Unreachable
             * @description True if the last WordPress status check failed.
             */
            wordpress_unreachable: boolean;
        };
        /** RequestChangesRequest */
        RequestChangesRequest: {
            /**
             * Client Name
             * @description The client's name.
             */
            client_name: string;
            /**
             * Comment
             * @description What the client wants changed.
             */
            comment: string;
            /**
             * Version
             * @description The version the client is reading.
             */
            version: number;
        };
        /** ReviewActionOut */
        ReviewActionOut: {
            /**
             * Id
             * @description Article id.
             */
            id: string;
            /** @description Status after the action. */
            status: components["schemas"]["Status"];
        };
        /** ReviewArticleOut */
        ReviewArticleOut: {
            /**
             * Body Html
             * @description Article body, as HTML.
             */
            body_html: string;
            /**
             * Id
             * @description Article id.
             */
            id: string;
            /**
             * Sent For Review At
             * @description When the agency last sent it for review, UTC.
             */
            sent_for_review_at?: string | null;
            /**
             * Slug
             * @description URL slug.
             */
            slug: string;
            /** @description Current lifecycle status. */
            status: components["schemas"]["Status"];
            /**
             * Title
             * @description Article title.
             */
            title: string;
            /**
             * Version
             * @description Increments on every body edit.
             */
            version: number;
        };
        /** ReviewLinkOut */
        ReviewLinkOut: {
            /**
             * Created At
             * Format: date-time
             * @description When this token was generated, UTC.
             */
            created_at: string;
            /**
             * Url
             * @description Full review link URL, built from the plaintext token.
             */
            url: string;
        };
        /** ReviewPageOut */
        ReviewPageOut: {
            /**
             * Published
             * @description Already live.
             */
            published: components["schemas"]["ArticleCard"][];
            /**
             * Site Name
             * @description The site's name.
             */
            site_name: string;
            /**
             * Upcoming
             * @description Scheduled to publish.
             */
            upcoming: components["schemas"]["ArticleCard"][];
            /**
             * Waiting
             * @description Awaiting the client's review.
             */
            waiting: components["schemas"]["ArticleCard"][];
            /**
             * Wordpress Unreachable
             * @description True if the last WordPress status check failed.
             */
            wordpress_unreachable: boolean;
        };
        /** ScheduleRequest */
        ScheduleRequest: {
            /**
             * Publish At
             * Format: date-time
             * @description Publish time, as an ISO 8601 datetime with a UTC offset.
             */
            publish_at: string;
        };
        /** SessionRequest */
        SessionRequest: {
            /**
             * Id Token
             * @description Firebase ID token from the client-side sign-in.
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6...
             */
            id_token: string;
        };
        /** SiteConnectionTest */
        SiteConnectionTest: {
            /**
             * Wp App Password
             * @description WordPress application password. Stored encrypted; never echoed back.
             */
            wp_app_password: string;
            /**
             * Wp Base Url
             * @description WordPress site base URL, e.g. https://client.example.com.
             */
            wp_base_url: string;
            /**
             * Wp Username
             * @description WordPress username for the application password.
             */
            wp_username: string;
        };
        /** SiteCreate */
        SiteCreate: {
            /**
             * Name
             * @description Display name for the site, e.g. the client's name.
             */
            name: string;
            /**
             * Wp App Password
             * @description WordPress application password. Stored encrypted; never echoed back.
             */
            wp_app_password: string;
            /**
             * Wp Base Url
             * @description WordPress site base URL, e.g. https://client.example.com.
             */
            wp_base_url: string;
            /**
             * Wp Username
             * @description WordPress username for the application password.
             */
            wp_username: string;
        };
        /** SiteOut */
        SiteOut: {
            /**
             * Connection Checked At
             * @description When WordPress was last checked, UTC.
             */
            connection_checked_at?: string | null;
            /**
             * Connection Ok
             * @description Whether the last WordPress check passed.
             */
            connection_ok: boolean;
            /**
             * Id
             * @description Site id.
             */
            id: string;
            /**
             * Name
             * @description Display name.
             */
            name: string;
            /**
             * Wp Base Url
             * @description WordPress site base URL.
             */
            wp_base_url: string;
            /**
             * Wp Username
             * @description WordPress username the app password belongs to.
             */
            wp_username: string;
        };
        /** SiteSummary */
        SiteSummary: {
            /**
             * Article Count
             * @description Articles in this site.
             */
            article_count: number;
            /**
             * Connection Checked At
             * @description When WordPress was last checked, UTC.
             */
            connection_checked_at?: string | null;
            /**
             * Connection Ok
             * @description Whether the last WordPress check passed.
             */
            connection_ok: boolean;
            /**
             * Id
             * @description Site id.
             */
            id: string;
            /**
             * Name
             * @description Display name.
             */
            name: string;
            /**
             * Needs Attention Count
             * @description Articles that are Failed or carry a sync warning.
             */
            needs_attention_count: number;
            /**
             * Wp Base Url
             * @description WordPress site base URL.
             */
            wp_base_url: string;
            /**
             * Wp Username
             * @description WordPress username the app password belongs to.
             */
            wp_username: string;
        };
        /** SiteUpdate */
        SiteUpdate: {
            /**
             * Name
             * @description New display name.
             */
            name?: string | null;
            /**
             * Wp App Password
             * @description New application password. Omitted or empty keeps the stored one.
             */
            wp_app_password?: string | null;
            /**
             * Wp Base Url
             * @description New WordPress site base URL.
             */
            wp_base_url?: string | null;
            /**
             * Wp Username
             * @description New WordPress username.
             */
            wp_username?: string | null;
        };
        /** SitesOut */
        SitesOut: {
            /**
             * Sites
             * @description Every site the agency manages.
             */
            sites: components["schemas"]["SiteSummary"][];
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "draft" | "awaiting_approval" | "changes_requested" | "approved" | "scheduled" | "published" | "failed";
        /**
         * SyncWarning
         * @enum {string}
         */
        SyncWarning: "late" | "changed_in_wordpress" | "missing_in_wordpress";
        /** UpcomingEntry */
        UpcomingEntry: {
            /**
             * Article Id
             * @description Article id.
             */
            article_id: string;
            /**
             * Publish At Utc
             * Format: date-time
             * @description Scheduled publish time, UTC.
             */
            publish_at_utc: string;
            /**
             * Title
             * @description Article title.
             */
            title: string;
        };
        /** UploadFileResult */
        UploadFileResult: {
            /** @description The created article, if import succeeded. */
            article?: components["schemas"]["ArticleSummary"] | null;
            /**
             * Code
             * @description Error code, if import failed.
             */
            code?: string | null;
            /**
             * Filename
             * @description Name of the uploaded file.
             */
            filename: string;
            /**
             * Ok
             * @description Whether this file was imported successfully.
             */
            ok: boolean;
            /**
             * Warnings
             * @description Import warnings for the created article, e.g. dropped images.
             * @default []
             */
            warnings: string[];
        };
        /** UploadResponse */
        UploadResponse: {
            /**
             * Results
             * @description One result per uploaded file, in request order.
             */
            results: components["schemas"]["UploadFileResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_route_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_review_review__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_article_route_review__token__articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewArticleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_route_review__token__articles__article_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_changes_route_review__token__articles__article_id__request_changes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestChangesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_route_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitesOut"];
                };
            };
        };
    };
    create_site_route_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_route_sites_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteConnectionTest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site_route_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site_route_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_sites__site_id__articles_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["Status"] | null;
            };
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paste_article_sites__site_id__articles_paste_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticlePaste"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_articles_sites__site_id__articles_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_articles_sites__site_id__articles_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_sites__site_id__articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_article_route_sites__site_id__articles__article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_article_sites__site_id__articles__article_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_back_route_sites__site_id__articles__article_id__pull_back_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_route_sites__site_id__articles__article_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_route_sites__site_id__articles__article_id__schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_for_review_route_sites__site_id__articles__article_id__send_for_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unschedule_route_sites__site_id__articles__article_id__unschedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_sites__site_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_link_sites__site_id__review_link_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_review_link_route_sites__site_id__review_link_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_site_connection_route_sites__site_id__test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
