/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paste Article */
        post: operations["paste_article_articles_paste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Articles */
        post: operations["upload_articles_articles_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Article */
        patch: operations["update_article_articles__article_id__patch"];
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session Route */
        post: operations["create_session_route_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleDetail */
        ArticleDetail: {
            /**
             * Approved Version
             * @description Version the client approved, if any.
             */
            approved_version?: number | null;
            /**
             * Body Html
             * @description Article body, as HTML.
             */
            body_html: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation time, UTC.
             */
            created_at: string;
            /**
             * Events
             * @description History log, oldest first.
             * @default []
             */
            events: components["schemas"]["EventOut"][];
            /**
             * Id
             * @description Article id.
             */
            id: string;
            /**
             * Last Checked At
             * @description Last WordPress status check time.
             */
            last_checked_at?: string | null;
            /**
             * Last Error
             * @description Error from the last failed WordPress call.
             */
            last_error?: string | null;
            /**
             * Publish At Utc
             * @description Scheduled publish time, UTC.
             */
            publish_at_utc?: string | null;
            /**
             * Published Url
             * @description Live URL, once published.
             */
            published_url?: string | null;
            /**
             * Slug
             * @description URL slug.
             */
            slug: string;
            /**
             * Source
             * @description How the article was imported: paste or docx.
             */
            source: string;
            /**
             * Source Filename
             * @description Original filename, if imported from a file.
             */
            source_filename?: string | null;
            /** @description Current lifecycle status. */
            status: components["schemas"]["Status"];
            /** @description Warning from the last WordPress status check, if any. */
            sync_warning?: components["schemas"]["SyncWarning"] | null;
            /**
             * Title
             * @description Article title.
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time, UTC.
             */
            updated_at: string;
            /**
             * Version
             * @description Increments on every body edit.
             */
            version: number;
            /**
             * Warnings
             * @description Warnings produced during import.
             * @default []
             */
            warnings: string[];
            /**
             * Wp Post Id
             * @description WordPress post id, once sent.
             */
            wp_post_id?: number | null;
        };
        /** ArticlePaste */
        ArticlePaste: {
            /**
             * Html
             * @description Pasted article HTML, raw body capped at 2 MB.
             */
            html: string;
        };
        /** ArticleSummary */
        ArticleSummary: {
            /**
             * Id
             * @description Article id.
             */
            id: string;
            /**
             * Publish At Utc
             * @description Scheduled publish time, UTC.
             */
            publish_at_utc?: string | null;
            /**
             * Slug
             * @description URL slug.
             */
            slug: string;
            /** @description Current lifecycle status. */
            status: components["schemas"]["Status"];
            /** @description Warning from the last WordPress status check, if any. */
            sync_warning?: components["schemas"]["SyncWarning"] | null;
            /**
             * Title
             * @description Article title.
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time, UTC.
             */
            updated_at: string;
        };
        /** ArticleUpdate */
        ArticleUpdate: {
            /**
             * Body Html
             * @description New body HTML, cleaned like import, capped at 2 MB.
             */
            body_html?: string | null;
            /**
             * Slug
             * @description New slug: lowercase letters, digits, hyphens.
             */
            slug?: string | null;
            /**
             * Title
             * @description New title.
             */
            title?: string | null;
        };
        /** Body_upload_articles_articles_upload_post */
        Body_upload_articles_articles_upload_post: {
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /** EventOut */
        EventOut: {
            /**
             * Actor
             * @description Who or what triggered the event.
             */
            actor: string;
            /**
             * At
             * Format: date-time
             * @description When the event happened, UTC.
             */
            at: string;
            /**
             * Data
             * @description The comment or error attached to this event.
             */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * @description Event id.
             */
            id: string;
            /** @description What happened. */
            type: components["schemas"]["EventType"];
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "imported" | "edited" | "sent_for_review" | "pulled_back" | "approved" | "changes_requested" | "scheduled" | "date_changed" | "published" | "failed" | "retried" | "ai_draft_created" | "ai_draft_accepted";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SessionRequest */
        SessionRequest: {
            /**
             * Id Token
             * @description Firebase ID token from the client-side sign-in.
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6...
             */
            id_token: string;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "draft" | "awaiting_approval" | "changes_requested" | "approved" | "scheduled" | "published" | "failed";
        /**
         * SyncWarning
         * @enum {string}
         */
        SyncWarning: "late" | "changed_in_wordpress" | "missing_in_wordpress";
        /** UploadFileResult */
        UploadFileResult: {
            /** @description The created article, if import succeeded. */
            article?: components["schemas"]["ArticleSummary"] | null;
            /**
             * Code
             * @description Error code, if import failed.
             */
            code?: string | null;
            /**
             * Filename
             * @description Name of the uploaded file.
             */
            filename: string;
            /**
             * Ok
             * @description Whether this file was imported successfully.
             */
            ok: boolean;
        };
        /** UploadResponse */
        UploadResponse: {
            /**
             * Results
             * @description One result per uploaded file, in request order.
             */
            results: components["schemas"]["UploadFileResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_articles_articles_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["Status"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ArticleSummary"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paste_article_articles_paste_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticlePaste"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_articles_articles_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_articles_articles_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_article_articles__article_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_route_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
