from typing import Protocol

from app.core.domain.models import Article, Event, Site
from app.core.domain.statuses import Status


class ArticleRepository(Protocol):
    def ensure_site_bootstrapped(self, name: str, wp_base_url: str) -> Site: ...

    def get_site(self) -> Site: ...

    def list_articles(self, status: Status | None = None) -> list[Article]: ...

    def get_article(self, article_id: str) -> Article | None: ...

    def create_article(self, article: Article) -> Article: ...

    def save_article(self, article: Article, event: Event | None = None) -> Article: ...

    def list_events(self, article_id: str) -> list[Event]: ...
