from typing import Protocol

from app.core.domain.models import Site


class SiteRepository(Protocol):
    def list_sites(self) -> list[Site]: ...

    def create_site(self, site: Site) -> Site: ...

    def save_site(self, site: Site) -> Site: ...

    def get_site(self, site_id: str) -> Site | None: ...

    def find_site_id_by_review_token_hash(self, token_hash: str) -> str | None: ...
